Updated Module Definition
root-community/root-insurance-ruby pull request #1
Opened 2018-10-02 14:49 UTC by rijnhardtkotze

2018-10-02 23:57 UTC, glasnoster commented on lib/root_insurance/api/quote.rb
> +      end
Hey @rijnhardtkotze,

@houndci-bot is right - please remove the extra whitespace after the `end`

2018-10-03 00:14 UTC, lm-pretorius requested changes
Hey @rijnhardtkotze!

Thanks for the PR!
I've left a few comments, all about styling.

Although styling is not crucial, a codebase can get a bit messy if everyone contributing doesn't follow the same style guide. That's why we added @houndci-bot to this project to force us to be consistent.

A bunch of the styling issues are my fault and if you don't feel like fixing them, please don't bother - I can do it right after I merge your PR.

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/application.rb
> +                            serial_number: nil, spouse_id: nil, children_ids: nil, extended_famliy_ids: nil)
Let's make `policyholder_id` and `serial_number` line up.

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/application.rb
> +end
Newlines at the end of files to keep the coding gods happy.

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/quote.rb
> +      # [cover_amount (Integer)]   Amount to cover, in cents. Should be between R10k and R50k, inclusive.
For documentation we can ignore Hound

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/quote.rb
> +      private
Please also fix this, if you don't mind.

It's actually my fault, but I think we should just follow Hound's standards, especially if more people will be contributing to this project in the future.

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/quote.rb
> +
Tbh I don't know what Hound is on about here. Let's leave this for now...

2018-10-03 00:14 UTC, glasnoster commented on lib/root_insurance/api/quote.rb
> +          basic_income_per_month: opts[:basic_income_per_month],
Yup, let's remove that last comma. It is probably me again...

2018-10-03 05:54 UTC, rijnhardtkotze commented
@glasnoster 

Updated the styling fixes. I think it is ready for merge now.

2018-10-03 10:39 UTC, lm-pretorius approved these changes

2018-10-03 10:40 UTC, merged